# Generated by Django 2.1.5 on 2019-03-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('req_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to=settings.AUTH_USER_MODEL)),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
