# Generated by Django 2.1.5 on 2019-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthread',
            old_name='therad',
            new_name='thread',
        ),
    ]
