# Generated by Django 2.1.5 on 2019-03-22 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_chat', '0003_remove_userthread_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedMesssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_Name',
            new_name='thread_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_for_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_group',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='deletedmesssage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_chat.Message'),
        ),
        migrations.AddField(
            model_name='deletedmesssage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
