# Generated by Django 2.1.5 on 2019-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailverify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
